version: '3.8'

services:
  kafka:
    container_name: kafka
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs

  filterdb:
    container_name: filterdb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - filterdb_data:/data/db

  invoicedb:
    container_name: invoicedb
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - invoicedb_data:/data/db

  maintenancedb:
    container_name: maintenancedb
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_TCP_PORT=3306
      - VIRTUAL_PORT=3306
    volumes:
      - maintenancedb_data:/data/db

  paymentdb:
    container_name: paymentdb
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_TCP_PORT=3307
      - VIRTUAL_PORT=3307
    volumes:
      - paymentdb_data:/data/db


volumes:
  kafka_data:
  filterdb_data:
  invoicedb_data:
  maintenancedb_data:
  paymentdb_data:





#  docker-compose up -d
#  docker-compose -p test-group up -d